version: '3.7'

services:
  db:
    image: postgres
    env_file:
      - ./config/.env
    volumes:
      - profitinfoplus_postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

volumes:
  profitinfoplus_postgres_data: