# Generated by Django 4.2.4 on 2023-09-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spendstatistic',
            old_name='conversions',
            new_name='conversion',
        ),
    ]
